# Copyright 2016, EMC, Inc.

version: '2'

volumes:
  dhcp-leases:
    external: false

services:

  #### Dependent Services / Functions ####
  rackhd_rabbitmq:
    image: rabbitmq:${RABBIT_MQ_TAG}
    environment:
      - RABBITMQ_ERLANG_COOKIE=homer_simpson
    container_name: amqp
    hostname: amqp
    dns: 172.17.0.1
    network_mode: "bridge"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
    expose:
      - "5672"
      - "15672"
      - "5671"
    restart: unless-stopped

  rackhd_consul:
    image: consul:${CONSUL_TAG}
    container_name: consul
    hostname: consul
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    network_mode: bridge
    depends_on:
      - rackhd_rabbitmq
    dns: 172.17.0.1
    restart: unless-stopped

  # RackHD depends on a Mongo Database for storage
  rackhd_mongo: # 27017
    image: mongo:latest
    container_name: rackhd-mongodb
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    restart: unless-stopped
  # TODO: Map this out to the /opt/dell/cpsd folder for debug

  # The DHCP Service works with their proxy for PXE
  # This one gets privilege and host networking to hook
  # the eth1 interface
  rackhd_dhcp: # 67/udp
    image: rackhd/isc-dhcp-server
    container_name: rackhd-dhcp-server
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    volumes:
      - "dhcp-leases:/var/lib/dhcp"
      - "../conf/dhcp/config:/etc/dhcp"
      - "../conf/dhcp/defaults:/etc/defaults"
    restart: unless-stopped

  # The Files Container pulls static files for discovery
  rackhd_files:
    image: rackhd/files:${TAG}
    container_name: rackhd-files
    network_mode: "none"
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    volumes:
      - "../files/mount:/RackHD/files"
    restart: unless-stopped
  # TODO: Extend this to include additional static assets


  #### RackHD services ####

  # RackHD dhcp proxy to keep track of leases
  rackhd_dhcp_proxy: # 68/udp, 4011
    image: rackhd/on-dhcp-proxy:${TAG}
    container_name: rackhd-dhcp-proxy
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
      - rackhd_dhcp
      - rackhd_mongo
    volumes:
      - "dhcp-leases:/var/lib/dhcp"
      - "../conf/monorail:/opt/monorail"
    restart: unless-stopped

  # RackHD API interfaces container
  rackhd_http: # 9090, 9080
    image: rackhd/on-http:${TAG}
    container_name: rackhd-http
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
      - rackhd_files
      - rackhd_mongo
    volumes:
      - "../files/mount/common:/RackHD/on-http/static/http/common"
      - "../iso:/RackHD/on-http/static/http"
      - "../conf/monorail:/opt/monorail"
    restart: unless-stopped


  # RackHD Syslog Service
  rackhd_syslog: # 514/udp
    image: rackhd/on-syslog:${TAG}
    container_name: rackhd-syslog
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
      - rackhd_mongo
    volumes:
      - "../conf/monorail:/opt/monorail"
    restart: unless-stopped


  # RackHD workflow engine
  rackhd_taskgraph:
    image: rackhd/on-taskgraph:${TAG}-symphony
    container_name: rackhd-taskgraph
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
      - rackhd_dhcp
      - rackhd_mongo
      - rackhd_syslog
    volumes:
      - "../conf/monorail:/opt/monorail"
    restart: unless-stopped


  # RackHD TFTP Service for kickstart/pxe startup
  rackhd_tftp: # 69/udp
    image: rackhd/on-tftp:${TAG}
    container_name: rackhd-tftp
    network_mode: "host"
    extra_hosts:
      - amqp:${AMQP_HOST}
      - mongo:${MONGO_HOST}
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
      - rackhd_files
      - rackhd_mongo
      - rackhd_syslog
    volumes:
      - "../files/mount:/RackHD/on-tftp/static/tftp"
      - "../conf/monorail:/opt/monorail"
    restart: unless-stopped
    
  # RackHD on-network Service for switch configuration.
  rackhd_network:
    image: rackhd/on-network
    container_name: rackhd_network
    network_mode: "host"
    environment:
    - SERVICE_PORT=33080
    - SERVICE_USERNAME=admin
    - SERVICE_PASSWORD=Password123!
    - CISCO_BOOT_TIME_IN_SECONDS=20
    - CISCO_INSTALL_TIME_IN_MINUTES=4
    - CISCO_RECONNECTION_TIMEOUT_IN_SECONDS=240
    - SWITCH_MODELS_FILE_PATH=switchModels.yml
    restart: unless-stopped

  gateway:
    container_name: gateway
    image: rackhd/gateway:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46020:46020
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    mem_limit: 512m
    environment:
    - "GATEWAY_HOST=${HOST_IP}"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k
    restart: unless-stopped

  device-discovery:
    container_name: device-discovery
    image: rackhd/device-discovery:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46002:46002
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss228k
    restart: unless-stopped

  dell-server-action:
    container_name: dell-server-action
    image: rackhd/dell-server-action:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46007:46007
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k
    restart: unless-stopped

  dell-chassis-inventory:
    container_name: dell-chassis-inventory
    image: rackhd/dell-chassis-inventory:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46001:46001
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k
    restart: unless-stopped

  dell-server-inventory:
    container_name: dell-server-inventory
    image: rackhd/dell-server-inventory:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46011:46011
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k
    restart: unless-stopped

  dell-server-configuration-profile:
    container_name: dell-server-configuration-profile
    # Using devel here to get latest SMI SCP fixes
    image: rackhd/dell-server-configuration-profile:devel
    network_mode: "host"
    ports:
    - 46018:46018
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    privileged: true
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k
    restart: unless-stopped

  dell-server-firmwareupdate:
    container_name: dell-server-firmwareupdate
    image: rackhd/dell-server-firmwareupdate:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46010:46010
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    privileged: true
    #volumes:
    #- /var/log/dell:/var/log/dell
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k
    restart: unless-stopped

  virtualnetwork:
    container_name: virtualnetwork
    image: rackhd/virtualnetwork:${SMI_TAG}
    depends_on:
    - postgresql
    network_mode: "host"
    ports:
    - 46016:46016
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl/
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k
    restart: unless-stopped

  virtualidentity:
    container_name: virtualidentity
    image: rackhd/virtualidentity:${SMI_TAG}
    depends_on:
    - postgresql
    network_mode: "host"
    ports:
    - 46015:46015
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k
    restart: unless-stopped

  dell-powerthermal-monitoring:
    container_name: dell-powerthermal-monitoring
    image: rackhd/dell-powerthermal-monitoring:${SMI_TAG}
    network_mode: "host"
    ports:
    - 46019:46019
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    #volumes:
    #- /var/log/dell/:/var/log/dell/
    #- /etc/ssl/:/etc/ssl
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k
    restart: unless-stopped

  swagger-aggregator:
    container_name: swagger-aggregator
    image: rackhd/swagger-aggregator:${SMI_TAG}
    #command: --add-host localhost -h service-resources
    network_mode: "host"
    ports:
    - 46021:46021
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    extra_hosts:
    - "service-registry:${REGISTRY_IP}"
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=consul"
    - "SWAGGER_HOST=http://${HOST_IP}"
    - _JAVA_OPTIONS=-Xmx512m -Xss256k
    restart: unless-stopped

  postgresql:
    container_name: postgresql
    image: postgres:9.6.1-alpine
    ports:
    - 5433:5432
    mem_limit: 512m
    depends_on:
      - rackhd_rabbitmq
      - rackhd_consul
    environment:
      - POSTGRES_PASSWORD=Dell123$$
    restart: unless-stopped
